#!/bin/bash
docker rm -f charming_curran

docker run -d --name charming_curran -p 8000:8000 -p 8443:8443 \
-e KONG_VITALS=off \
-e KONG_CLUSTER_TELEMETRY_SERVER_NAME=83897e20f5.us.tp.konghq.com \
-e KONG_CLUSTER_CERT="-----BEGIN CERTIFICATE-----
MIICHTCCAcSgAwIBAgIBATAKBggqhkjOPQQDBDBAMT4wCQYDVQQGEwJVUzAxBgNV
BAMeKgBrAG8AbgBuAGUAYwB0AC0ATABvAGMAYQBsACAARwBhAHQAZQB3AGEAeTAe
Fw0yNjAzMjMxMzQ2NTJaFw0zNjAzMjMxMzQ2NTJaMEAxPjAJBgNVBAYTAlVTMDEG
A1UEAx4qAGsAbwBuAG4AZQBjAHQALQBMAG8AYwBhAGwAIABHAGEAdABlAHcAYQB5
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAENI2f0P4XvO9gr0RNuDtBCpASxJBo
WNNXoZLvgG5WH+8pPxJuE9I7JVuF+21XrV88SwRWXq3eQ909woGZnz+WpKOBrjCB
qzAMBgNVHRMBAf8EAjAAMAsGA1UdDwQEAwIABjAdBgNVHSUEFjAUBggrBgEFBQcD
AQYIKwYBBQUHAwIwFwYJKwYBBAGCNxQCBAoMCGNlcnRUeXBlMCMGCSsGAQQBgjcV
AgQWBBQBAQEBAQEBAQEBAQEBAQEBAQEBATAcBgkrBgEEAYI3FQcEDzANBgUpAQEB
AQIBCgIBFDATBgkrBgEEAYI3FQEEBgIEABQACjAKBggqhkjOPQQDBANHADBEAiBk
6tttV7YJB43V8srs46hurlAs9zwdZ/Bv3f2VIAviogIgCNamOMYbFk8TyDT30T7n
IHDBl5PMSOu9fGatVUiMSYI=
-----END CERTIFICATE-----" \
-e KONG_ROUTER_FLAVOR=expressions \
-e KONG_CLUSTER_MTLS=pki \
-e KONG_CLUSTER_CONTROL_PLANE=83897e20f5.us.cp.konghq.com:443 \
-e KONG_CLUSTER_SERVER_NAME=83897e20f5.us.cp.konghq.com \
-e KONG_CLUSTER_TELEMETRY_ENDPOINT=83897e20f5.us.tp.konghq.com:443 \
-e KONG_CLUSTER_CERT_KEY="-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQghD1E05q822l4zTEU
Y6rVoNzuCDLw+UMvxEhvKkg/5lagCgYIKoZIzj0DAQehRANCAAQ0jZ/Q/he872Cv
RE24O0EKkBLEkGhY01ehku+AblYf7yk/Em4T0jslW4X7bVetXzxLBFZerd5D3T3C
gZmfP5ak
-----END PRIVATE KEY-----" \
-e KONG_LUA_SSL_TRUSTED_CERTIFICATE=system \
-e KONG_KONNECT_MODE=on \
-e KONG_ROLE=data_plane \
-e KONG_DATABASE=off \
-e KONG_TRACING_INSTRUMENTATIONS=all \
kong/kong-gateway:3.13
